import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'
import AppHeader from '../components/AppHeader'
import api from '../lib/api'
import jsPDF from 'jspdf'
import {
  ArrowLeft,
  RefreshCw,
  Download,
  ClipboardCopy,
  Check,
  Shield,
  Users,
  FileText,
  Clock,
} from 'lucide-react'

interface HandoffData {
  summary: string
  patient_count: number
  conversation_count: number
  pending_flags: Array<{ type: string; severity: string; message: string; suggestion: string }>
  generated_at: string
}

export default function ShiftHandoff() {
  const navigate = useNavigate()
  const { user } = useAuth()
  const [handoff, setHandoff] = useState<HandoffData | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [copied, setCopied] = useState(false)

  const generateHandoff = async () => {
    setLoading(true)
    setError('')
    try {
      const res = await api.post('/conversations/handoff', {})
      setHandoff(res.data)
    } catch (err: any) {
      setError(err?.response?.data?.detail || 'Failed to generate handoff summary')
    } finally {
      setLoading(false)
    }
  }

  const copyToClipboard = () => {
    if (!handoff) return
    navigator.clipboard.writeText(handoff.summary)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const downloadHandoffPdf = () => {
    if (!handoff) return
    const doc = new jsPDF({ unit: 'mm', format: 'a4' })
    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 20
    const contentWidth = pageWidth - margin * 2
    let y = 0

    // Navy header
    doc.setFillColor(30, 58, 95)
    doc.rect(0, 0, pageWidth, 35, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.text('Shift Handoff Summary', margin, 16)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    doc.text(`${user?.full_name || 'Physician'} — ${new Date().toLocaleDateString()}`, margin, 26)

    y = 45

    // Stats
    doc.setTextColor(30, 58, 95)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text(`Patients: ${handoff.patient_count}  |  Conversations: ${handoff.conversation_count}  |  Risk Flags: ${handoff.pending_flags.length}`, margin, y)
    y += 10

    // Divider
    doc.setDrawColor(229, 231, 235)
    doc.setLineWidth(0.5)
    doc.line(margin, y, pageWidth - margin, y)
    y += 8

    // Body
    doc.setTextColor(31, 41, 55)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(handoff.summary, contentWidth)
    for (const line of lines) {
      if (y > 270) { doc.addPage(); y = 20 }
      doc.text(line, margin, y)
      y += 6
    }

    // Footer
    const footerY = doc.internal.pageSize.getHeight() - 10
    doc.setTextColor(156, 163, 175)
    doc.setFontSize(7)
    doc.text('Generated by CareBridge AI — Shift Handoff', pageWidth / 2, footerY, { align: 'center' })

    doc.save(`CareBridge_ShiftHandoff_${new Date().toISOString().split('T')[0]}.pdf`)
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-slate-900 transition-colors">
      <AppHeader />

      <main className="max-w-4xl mx-auto px-4 sm:px-6 py-8">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h2 className="text-xl font-bold text-body dark:text-slate-100">Shift Handoff</h2>
            <p className="text-sm text-muted dark:text-slate-400 mt-1">
              AI-generated summary for incoming physician
            </p>
          </div>
          <button
            onClick={() => navigate('/dashboard')}
            className="text-sm text-clinical hover:text-clinical-dark flex items-center gap-1"
          >
            <ArrowLeft className="w-4 h-4" /> Back to Dashboard
          </button>
        </div>

        {!handoff && !loading && (
          <div className="text-center py-16">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-navy/10 dark:bg-navy/30 mb-4">
              <Users className="w-8 h-8 text-navy dark:text-clinical" />
            </div>
            <h3 className="text-lg font-semibold text-body dark:text-slate-100 mb-2">
              Generate Shift Handoff
            </h3>
            <p className="text-muted dark:text-slate-400 text-sm mb-6 max-w-md mx-auto">
              Create an AI-powered handoff summary from all your conversations this shift.
              The incoming physician gets a one-page overview of patients, decisions, and pending items.
            </p>
            <button
              onClick={generateHandoff}
              className="px-8 py-3 bg-navy hover:bg-navy-dark text-white font-semibold rounded-xl transition-colors inline-flex items-center gap-2 shadow-lg"
            >
              <RefreshCw className="w-5 h-5" />
              Generate Handoff Summary
            </button>
          </div>
        )}

        {loading && (
          <div className="text-center py-16">
            <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-navy mx-auto mb-4" />
            <p className="text-muted dark:text-slate-400 text-sm">Analyzing conversations and generating handoff...</p>
          </div>
        )}

        {error && (
          <div className="text-sm text-danger bg-red-50 dark:bg-red-900/30 rounded-lg px-4 py-3 mb-4">
            {error}
          </div>
        )}

        {handoff && (
          <div className="space-y-6">
            {/* Stats bar */}
            <div className="grid grid-cols-3 gap-4">
              {[
                { icon: Users, label: 'Patients', value: handoff.patient_count },
                { icon: FileText, label: 'Conversations', value: handoff.conversation_count },
                { icon: Shield, label: 'Risk Flags', value: handoff.pending_flags.length },
              ].map(({ icon: Icon, label, value }) => (
                <div key={label} className="bg-white dark:bg-slate-800 rounded-xl p-4 border border-gray-100 dark:border-slate-700 text-center transition-colors">
                  <Icon className="w-5 h-5 text-navy dark:text-clinical mx-auto mb-1" />
                  <p className="text-2xl font-bold text-body dark:text-slate-100">{value}</p>
                  <p className="text-xs text-muted dark:text-slate-400">{label}</p>
                </div>
              ))}
            </div>

            {/* Handoff narrative */}
            <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm border border-gray-100 dark:border-slate-700 overflow-hidden transition-colors">
              <div className="px-6 py-4 border-b border-gray-100 dark:border-slate-700 flex items-center justify-between bg-gradient-to-r from-navy/5 dark:from-navy/20 to-transparent">
                <div className="flex items-center gap-2">
                  <Clock className="w-5 h-5 text-navy dark:text-clinical" />
                  <h3 className="font-bold text-body dark:text-slate-100">Handoff Summary</h3>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={copyToClipboard}
                    className="flex items-center gap-1 px-3 py-1.5 text-xs font-medium rounded-lg bg-navy/5 dark:bg-slate-700 hover:bg-navy/10 dark:hover:bg-slate-600 text-navy dark:text-slate-200 transition-colors"
                  >
                    {copied ? <><Check className="w-3 h-3" /> Copied!</> : <><ClipboardCopy className="w-3 h-3" /> Copy</>}
                  </button>
                  <button
                    onClick={downloadHandoffPdf}
                    className="flex items-center gap-1 px-3 py-1.5 text-xs font-medium rounded-lg bg-clinical/10 hover:bg-clinical/20 text-clinical transition-colors"
                  >
                    <Download className="w-3 h-3" /> PDF
                  </button>
                </div>
              </div>
              <div className="px-6 py-5">
                <div className="prose prose-sm dark:prose-invert max-w-none text-body dark:text-slate-200 leading-relaxed whitespace-pre-wrap">
                  {handoff.summary}
                </div>
              </div>
            </div>

            {/* Actions */}
            <div className="flex justify-center gap-3">
              <button
                onClick={generateHandoff}
                className="px-6 py-3 border border-gray-200 dark:border-slate-600 rounded-xl text-sm font-medium text-muted dark:text-slate-300 hover:bg-gray-50 dark:hover:bg-slate-800 transition-colors flex items-center gap-2"
              >
                <RefreshCw className="w-4 h-4" /> Regenerate
              </button>
              <button
                onClick={() => navigate('/dashboard')}
                className="px-6 py-3 bg-navy hover:bg-navy-dark text-white font-semibold rounded-xl transition-colors"
              >
                Done
              </button>
            </div>
          </div>
        )}
      </main>
    </div>
  )
}
