import jsPDF from 'jspdf'
import { fleschKincaidGrade, gradeSeverity } from './readability'

interface PdfOptions {
  hospitalName: string
  physicianName: string
  patientAlias: string
  familySummary: string
  date: string
  language?: string
}

export function generateFamilySummaryPdf(options: PdfOptions): void {
  const { hospitalName, physicianName, patientAlias, familySummary, date, language } = options
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  const contentWidth = pageWidth - margin * 2
  let y = 0

  // --- Navy header bar ---
  doc.setFillColor(30, 58, 95) // #1E3A5F navy
  doc.rect(0, 0, pageWidth, 35, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(hospitalName, margin, 16)

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text('Family Communication Summary', margin, 26)

  // Date on the right
  doc.setFontSize(9)
  doc.text(date, pageWidth - margin, 26, { align: 'right' })

  y = 45

  // --- Patient info ---
  doc.setTextColor(30, 58, 95)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text(`Patient: ${patientAlias}`, margin, y)
  y += 5
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(107, 114, 128) // muted
  doc.text(`Attending Physician: ${physicianName}`, margin, y)

  if (language && language !== 'english') {
    y += 5
    doc.text(`Language: ${language.charAt(0).toUpperCase() + language.slice(1)}`, margin, y)
  }

  y += 10

  // --- Divider ---
  doc.setDrawColor(229, 231, 235)
  doc.setLineWidth(0.5)
  doc.line(margin, y, pageWidth - margin, y)
  y += 8

  // --- Family summary body ---
  doc.setTextColor(31, 41, 55) // body color
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')

  const lines = doc.splitTextToSize(familySummary, contentWidth)
  for (const line of lines) {
    if (y > 265) {
      doc.addPage()
      y = 20
    }
    doc.text(line, margin, y)
    y += 6
  }

  y += 8

  // --- Readability badge ---
  const grade = fleschKincaidGrade(familySummary)
  const severity = gradeSeverity(grade)
  const badgeColor =
    severity === 'green' ? [34, 197, 94] : severity === 'yellow' ? [245, 158, 11] : [239, 68, 68]

  doc.setFillColor(badgeColor[0], badgeColor[1], badgeColor[2])
  doc.roundedRect(margin, y, 50, 7, 2, 2, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.text(`Reading Level: Grade ${grade}`, margin + 3, y + 5)
  y += 15

  // --- Divider ---
  if (y > 255) {
    doc.addPage()
    y = 20
  }
  doc.setDrawColor(229, 231, 235)
  doc.line(margin, y, pageWidth - margin, y)
  y += 10

  // --- Signature area ---
  doc.setTextColor(107, 114, 128)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('Physician Signature: _______________________________', margin, y)
  y += 8
  doc.text(`Printed Name: ${physicianName}`, margin, y)
  y += 8
  doc.text(`Date: ${date}`, margin, y)

  // --- Footer ---
  const footerY = doc.internal.pageSize.getHeight() - 10
  doc.setTextColor(156, 163, 175)
  doc.setFontSize(7)
  doc.text(
    'Generated by CareBridge AI — ICU Serious Illness Communication Platform',
    pageWidth / 2,
    footerY,
    { align: 'center' }
  )

  // Save
  const safeName = patientAlias.replace(/[^a-zA-Z0-9]/g, '_')
  doc.save(`CareBridge_FamilySummary_${safeName}.pdf`)
}
